CREATE TABLE IF NOT EXISTS documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content_type TEXT NOT NULL,
  source TEXT,
  chunk_index INTEGER,
  text_chunk TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
